Support for Short, Float and Double data types.
CodeSpartan/UE4TcpSocketPlugin pull request #23
Opened 2024-01-11 02:01 UTC by PantelisAndrianakis

Attempt to add support for Short, Float and Double data types.

2024-01-17 17:08 UTC, CodeSpartan commented
Thanks, I'll have a look over the weekend.

2024-01-20 13:21 UTC, CodeSpartan requested changes

2024-01-20 13:21 UTC, CodeSpartan commented on Source/TcpSocketPlugin/Public/TcpSocketConnection.h
> +	static TArray<uint8> Conv_ShortToBytes(int16 InShort)
Please move the function definition into .cpp
And do in-place initialization, e.g.
```cpp
return TArray<uint8> { 0, 1, 2 };
```

2024-01-20 13:21 UTC, CodeSpartan commented on Source/TcpSocketPlugin/Public/TcpSocketConnection.h
> +	static TArray<uint8> Conv_LongToBytes(int64 InLong)
Please move the function definition into .cpp
And unroll the loop into an in-place initialization

2024-01-20 13:21 UTC, CodeSpartan commented on Source/TcpSocketPlugin/Public/TcpSocketConnection.h
> +	static TArray<uint8> Conv_DoubleToBytes(double InDouble)
Please move the function definition into .cpp

2024-01-20 13:21 UTC, CodeSpartan commented on Source/TcpSocketPlugin/Public/TcpSocketConnection.h
> +	static int16 Message_ReadShort(UPARAM(ref) TArray<uint8>& Message)
Please move the function definition into .cpp

2024-01-20 13:21 UTC, CodeSpartan commented on Source/TcpSocketPlugin/Public/TcpSocketConnection.h
> +	static int64 Message_ReadLong(UPARAM(ref) TArray<uint8>& Message)
Please move the function definition into .cpp

2024-01-20 13:21 UTC, CodeSpartan commented on Source/TcpSocketPlugin/Public/TcpSocketConnection.h
> +	static double Message_ReadDouble(UPARAM(ref) TArray<uint8>& Message)
Please move the function definition into .cpp

2024-01-21 05:08 UTC, PantelisAndrianakis commented
I made two addition commits.
One for TcpSocketConnection.h removing function code from there.
And one for TcpSocketConnection.cpp moving functions there.

2024-01-22 13:07 UTC, CodeSpartan commented
Your PR doesn't compile: there's no `int16` type in blueprints, so it can't be exposed to blueprints. Leave the int16-related functions for C++ users, but don't expose them to blueprints. There's also some syntax errors.

In blueprints, Long is called Integer 64, so the blueprint names should conform. The double type in Blueprints is called a `Float (double-precision)`, so same thing here. The old `Read Float` should appear as `Read Float (single-precision)` and `Read Double` should appear as `Read Float (double-precision)`. Same with hover texts that are grabbed from the comments, like "Converts a float/double/long to an array of bytes" should feature new type names.
The C++ names should remain as they are now.

Please use in-place initialization of arrays, e.g.
```cpp
return TArray {
	static_cast<uint8>((InLong >> 56) & 0xFF),
	static_cast<uint8>((InLong >> 48) & 0xFF),
	//...
}
```
I know I've used `Array.Add()` in existing code, but those are previously made bad practices.

2024-01-23 21:13 UTC, PantelisAndrianakis commented
int16-related functions are needed so that you use less bandwidth on network transfer (eg player inventory item infos).
Same can be done with booleans but is very rare, so I did not add that.
On my server side short values are return as full int32 as well.
So I made the function to return an int32 as well.

I do not agree with naming conformations you proposed, Long and Double are self explainable.
A the end is a matter of taste, could also use D for int, L for long etc, but that would make them harder to read.

Used in-place initialization at Conv_LongToBytes.

2024-01-24 08:06 UTC, CodeSpartan commented
Merging your PR into a separate branch to align with Epic's naming standards and ensure functionality. Will make necessary adjustments before merging into main. Thank you for your contribution.

2024-01-24 08:06 UTC, merged